---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ k8s_tew_url }} to {{ k8s_tew_exe }}
  become: yes
  become_user: root
  get_url:
    url: '{{ k8s_tew_url }}'
    dest: '{{ k8s_tew_exe }}'
    mode: 0755
    checksum: '{{ k8s_tew_checksum }}'
- name: linking {{ k8s_tew_link }} to {{ k8s_tew_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ k8s_tew_exe }}'
    dest: '{{ k8s_tew_link }}'
    state: link
