---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ k8s_tew_url }} to {{ k8s_tew_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ k8s_tew_url }}'
    dest: '{{ k8s_tew_exe }}'
    mode: '755'
    checksum: '{{ k8s_tew_checksum }}'
- name: Linking {{ k8s_tew_link }} to {{ k8s_tew_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ k8s_tew_exe }}'
    dest: '{{ k8s_tew_link }}'
    state: link
